language: node_js

# node 8 as that's the version atom is currently on
node_js:
  - "8"

compiler: clang-3.6

env:
  - CXX=clang-3.6

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6

install:
  - npm install

script:
  - npm run build
  - npm run lint
  - npm run test

cache:
  directories:
    - node_modules
