sudo: false

language: node_js

# node 8 as that's the version atom is currently on
node_js:
  - "8"

install:
  - npm install

script:
  - npm run build
  - npm run lint
  - npm run test

cache:
  directories:
    - node_modules
